name: Build profile metrics

on:
  schedule:
    - cron: "0 3 * * *"   # se ejecuta diario a las 03:00 UTC
  workflow_dispatch:       # permite ejecutarlo manualmente

# Permisos para poder commitear metrics.svg en tu repo
permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: IDGS-901-22001379        # <- TU USUARIO
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City

          # === Calendario de contribuciones (heatmap anual) ===
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # === Hábitos (métricas por día/hora) - opcional, queda bonito
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_trim: yes

          # === Lenguajes y extras ===
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css
          plugin_achievements: yes
          plugin_traffic: yes

          # === Dónde guardar el archivo generado ===
          filename: metrics.svg
          committer_branch: main          # si tu rama por defecto es "master", cámbialo a master
          committer_message: "chore: update metrics"

