name: Generate Snake

on:
  schedule:
    - cron: "0 1 * * *"     # corre diario 01:00 UTC
  workflow_dispatch:         # permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Genera varias variantes del SVG:
      - name: Generate snake svgs
        uses: Platane/snk@v3
        with:
          github_user_name: IDGS-901-22001379   # <- tu usuario
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            # Variante personalizada: serpiente morada, fondo gris claro y verdes brillantes
            dist/snake-custom.svg?color_snake=%23a855f7&color_dots=%23f3f4f6,%23bbf7d0,%234cdf85,%2322c55e,%2316a34a&background=%23f3f4f6

      # Publica los SVG en la rama `output`
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

